// Base de données des analyses médicales du Maroc
// Extrait du catalogue officiel
// Prix en Dirhams marocains (DH)

// Signification des secteurs
window.SECTOR_NAMES = {
    "DTP": "Dosage Thérapeutique Pharmacologique",
    "LB": "Laboratoire de Biochimie",
    "LBM": "Laboratoire de Bactériologie et Microbiologie",
    "LH": "Laboratoire d'Hématologie",
    "LH/LP": "Laboratoire Hématologie/Parasitologie",
    "LIC": "Laboratoire d'Immunochimie",
    "LIS": "Laboratoire d'Immunosérologie",
    "LIS/LH": "Laboratoire Immunosérologie/Hématologie",
    "LP": "Laboratoire de Parasitologie",
    "LSM": "Laboratoire Spécialisé Métabolisme",
    "Labo. Spécialisé": "Laboratoire Spécialisé"
};

window.MEDICAL_DATABASE = [
    {code:"ACTU 0166",name:"*ACETONE URINE RECHERCHE",sector:"LB",delay:"2 jours",price:10.00,description:"Analyse urinaire. Diagnostic des infections et maladies rénales."},
    {code:"AU   1 0100",name:"ACIDE URIQUE (SANG)",sector:"LB",delay:"1 jour",price:30.00,description:"Dosage de l\'acide urique pour diagnostic de la goutte, calculs rénaux et surveillance du traitement. Évalue le métabolisme des purines."},
    {code:"AU2  1 0100",name:"ACIDE URIQUE (SANG) J2 (2ème jour)",sector:"LB",delay:"1 jour",price:30.00,description:"Dosage de l\'acide urique pour diagnostic de la goutte, calculs rénaux et surveillance du traitement. Évalue le métabolisme des purines."},
    {code:"AU3  1 0100",name:"ACIDE URIQUE (SANG) J3 (3ème jour)",sector:"LB",delay:"1 jour",price:30.00,description:"Dosage de l\'acide urique pour diagnostic de la goutte, calculs rénaux et surveillance du traitement. Évalue le métabolisme des purines."},
    {code:"AUU  1 0167",name:"ACIDE URIQUE (URINE)",sector:"LB",delay:"2 jours",price:30.00,description:"Dosage de l\'acide urique pour diagnostic de la goutte, calculs rénaux et surveillance du traitement. Évalue le métabolisme des purines."},
    {code:"AUU2 0167",name:"ACIDE URIQUE (URINE) J2 (2ème jour)",sector:"LB",delay:"2 jours",price:30.00,description:"Dosage de l\'acide urique pour diagnostic de la goutte, calculs rénaux et surveillance du traitement. Évalue le métabolisme des purines."},
    {code:"AUU3 0167",name:"ACIDE URIQUE (URINE) J3 (3ème jour)",sector:"LB",delay:"2 jours",price:30.00,description:"Dosage de l\'acide urique pour diagnostic de la goutte, calculs rénaux et surveillance du traitement. Évalue le métabolisme des purines."},
    {code:"AUUC CH62",name:"*ACIDE URIQUE (URINE) CRIS",sector:"LB",delay:"1 jour",price:30.00,description:"Dosage de l\'acide urique pour diagnostic de la goutte, calculs rénaux et surveillance du traitement. Évalue le métabolisme des purines."},
    {code:"LAC",name:"ACIDE LACTIQUE (LACTATES)",sector:"LB",delay:"A TELEPHONER",price:135.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"AM",name:"AMONIEMIE",sector:"LB",delay:"A TELEPHONER",price:230.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"ALD",name:"ALDOLASE",sector:"LB",delay:"A TELEPHONER",price:130.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CAI",name:"ACIDE RYRUVIQUE",sector:"LB",delay:"A TELEPHONER",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"FOL  4 HN",name:"*ACIDE FOLIQUE (FOLATES)",sector:"LIC",delay:"3 jours",price:400.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"VMA 0184",name:"*ACIDE VANYL MANDELIQUE (URINE24)",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:250.00,description:"Analyse urinaire. Diagnostic des infections et maladies rénales."},
    {code:"HVA 0185",name:"*ACIDE HOMOVANILIQUE (HPLC) UNINE 24",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:250.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"DEPAK HN",name:"*ACIDE VALPROIQUE (SANG)",sector:"DTP",delay:"A TELEPHONER",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"REIGA HN",name:"*AC ANTI-RETICULINE IGA",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:400.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"B2GLG",name:"*AC ANTI BETA2 GLUCOPROTEINE IGG",sector:"LIS",delay:"4 jours",price:200.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"B2GLM",name:"*AC ANTI BETA2 GLUCOPROTEINE IGM",sector:"LIS",delay:"4 jours",price:200.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"ACCOG",name:"*ANTICOAGULANTS CIRCULANTS",sector:"LIS",delay:"4 jours",price:205.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"INTRI 0392",name:"*AC ANTI-FACTEUR INTRINSEQUE",sector:"LIS",delay:"A TELEPHONER",price:450.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"LC",name:"*ANTI-LC1",sector:"LIS",delay:"A TELEPHONER",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"NUCL",name:"*AC ANTI-NUCLEOSOME",sector:"LIS",delay:"A TELEPHONER",price:575.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"CENTR",name:"*AC ANTI CENTROMERES",sector:"LIS",delay:"A TELEPHONER",price:150.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"RIBO",name:"*AC ANTI RIBOSOMES",sector:"LIS",delay:"A TELEPHONER",price:350.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"ILOT",name:"*AC ANTI-ILOTS DE LANGERHANS",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:200.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"RACH",name:"AC ANTI RECEPTEURS DE L’ACETHYLCHOLINE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:400.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"SLA",name:"*AC ANTI-SLA",sector:"LIS",delay:"A TELEPHONER",price:700.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"MBG",name:"*AC ANTI MEMBRANE BASALE GLOMERULAIRE",sector:"LIS",delay:"A TELEPHONER",price:300.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"GAD",name:"*ANTI-GADII (AC ANTI-ACIDE GLUTAMIQUE DECARBOXYLASE)",sector:"LIS",delay:"A TELEPHONER",price:200.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"RTSH",name:"*AC ANTI RECEPTEURS DE LA TSH",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:450.00,description:"Hormone thyréostimulante. Test de référence pour dépistage des dysfonctions thyroïdiennes."},
    {code:"SYNT",name:"* ANTI-SYNTHETHASES AC DES MYOSITES (PL7 ,PL12 , EJ , OJ , SRP , MI2 , KU ,PM/SCL)",sector:"LIS",delay:"A TELEPHONER",price:800.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"ATG 0346",name:"*ANTICORPS ANTITHYROGLOBULINE",sector:"LIC",delay:"3 jours",price:150.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"ATPO 0345",name:"*ANTICORPS  ANTITHYROPEROXYDASE",sector:"LIC",delay:"3 jours",price:150.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"GLIGA HN",name:"*AC ANTI-GLIADINE IGA",sector:"LIS",delay:"4 jours",price:200.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"GLIGG HN",name:"*AC ANTI-GLIADINE IGG",sector:"LIS",delay:"4 jours",price:200.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"CCP HN",name:"*ANTICORPS ANTI CCP (peptides citrulines cycliques)",sector:"LIS",delay:"4 jours",price:225.00,description:"Anti-peptides citrullinés. Marqueur spécifique et précoce de la polyarthrite rhumatoïde."},
    {code:"TRGLU HN",name:"*AC ANTI-TRANSGLUTAMINA",sector:"LIS",delay:"4 jours",price:200.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"ENIGA HN",name:"*AC ANTI-ENDOMYSIUM IGA",sector:"LIS",delay:"7 jours",price:200.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"ACPG HN",name:"*ANTICORPS ANTI-CELLULES PARIETALES",sector:"LIS",delay:"4 jours",price:150.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"ANCA HN",name:"*AC ANTI-CYTOPLASME DES PNN (ANCA)",sector:"LIS",delay:"7 jours",price:400.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"ANA 0344",name:"*ANTICORPS ANTI NUCLEAIRES",sector:"LIS",delay:"4 jours",price:150.00,description:"ANA. Dépistage des maladies auto-immunes systémiques (lupus, sclérodermie)."},
    {code:"ASMA HN",name:"*ANTICORPS ANTI MUSCLES LISSES",sector:"LIS",delay:"4 jours",price:150.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"CARDG HN",name:"*ANTICORPS ANTI CARDIOLIPINES IGG",sector:"LIS",delay:"4 jours",price:200.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"CARDM",name:"*ANTICORPS ANTI CARDIOLIPINES IGM",sector:"LIS",delay:"4 jours",price:200.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"DNA HN",name:"*ANTICORPS ANTI-DNA NATIF",sector:"LIS",delay:"4 jours",price:150.00,description:"Anticorps anti-DNA natif. Spécifique du lupus érythémateux systémique."},
    {code:"LKM1 HN",name:"*ANTICORPS ANTI LKM1",sector:"LIS",delay:"4 jours",price:200.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"RNP HN",name:"*ANTICORPS ANTI-RNP",sector:"LIS",delay:"4 jours",price:150.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"SCL70 HN",name:"*ANTICORPS ANTI-SCL70",sector:"LIS",delay:"4 jours",price:150.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"SM HN",name:"*ANTICORPS ANTI-SM",sector:"LIS",delay:"4 jours",price:150.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"SSA HN",name:"*ANTICORPS ANTI-SSA",sector:"LIS",delay:"4 jours",price:150.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"SSB HN",name:"*ANTICORPS ANTI-SSB",sector:"LIS",delay:"4 jours",price:150.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"EBNA  1 0332",name:"*AC ANTI-EBNA (IGG)",sector:"LIS",delay:"1 jour",price:180.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"VCAG  1 0333",name:"*AC ANTI-VCA (IGG) / EA (IGG)",sector:"LIS",delay:"1 jour",price:180.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"AMA 0393",name:"*ANTICORPS ANTI MITOCHONDRIES",sector:"LIS",delay:"4 jours",price:200.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"VCAM  1 199",name:"*AC ANTI-VCA IGM",sector:"LIS",delay:"1 jour",price:180.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"JO1 IS6E",name:"*AC ANTI-JO1",sector:"LIS",delay:"4 jours",price:150.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"ACT 1",name:"ANTI-Actine",sector:"LIS",delay:"8 jours",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"AFP 2 0.357",name:"AFP (ALPHA FOETOPROTEINE)",sector:"LIC",delay:"1 jour",price:250.00,description:"Alpha-fœtoprotéine. Marqueur tumoral hépatique et surveillance de grossesse."},
    {code:"CIRAI 0225",name:"*AGGLU IRREGULIERES RECHERCHE(RAI)",sector:"LH",delay:"2 jours",price:40.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"ACE  2 0356",name:"ANTIGENE CARCINO EMBRYONNAIRE",sector:"LIC",delay:"1 jour",price:250.00,description:"Immunoglobulines E. Diagnostic des allergies et maladies parasitaires."},
    {code:"LCRAG 0201",name:"ANTIGENES SOLUBLES BAC",sector:"LBM",delay:"0 jour",price:250.00,description:"Immunoglobulines E. Diagnostic des allergies et maladies parasitaires."},
    {code:"ASLO 0266",name:"*ANTISTREPTOLYSINE (ASLO)",sector:"LP",delay:"1 jour",price:80.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"ASD 2 0264",name:"*ANTISTREPTODORNASE(ASD)",sector:"LP",delay:"A TELEPHONER",price:100.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"AT3 HN",name:"*ANTI THROMBINE 3",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:200.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"ALB12 0177",name:"ALBUMINE URINE DOSAGE (Urine 12h)",sector:"LB",delay:"2 jours",price:120.00,description:"Principale protéine du sang. Évalue l\'état nutritionnel et la fonction hépatique."},
    {code:"ALB 2 0101",name:"ALBUMINE (SANG)",sector:"LB",delay:"1 jour",price:60.00,description:"Principale protéine du sang. Évalue l\'état nutritionnel et la fonction hépatique."},
    {code:"A2MA HN",name:"*ALPHA2 MACROGLOBULINE",sector:"LP",delay:"1 jour",price:200.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"APOA 0122",name:"*APO A1",sector:"LP",delay:"1 jour",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"APOB 0123",name:"*APO B",sector:"LP",delay:"1 jour",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"ASPER 0292",name:"*ASPERGILOSE SERODIAGNOSTIC",sector:"LIS",delay:"1 jour",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"TOXAV HN",name:"*AVIDITE DES IGG ANTI-TOXOPLASMA GON",sector:"LIS",delay:"1 jour",price:200.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"QAGBS 1",name:"*AG HBS QUANTITATIF",sector:"LIS",delay:"2 jours",price:250.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"BARB HN",name:"*BARBITEMIE-PHENOBARBITAL (SANG)",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:200.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"BENZ HN",name:"*BENZODIAZEPINES (URINES)",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:300.00,description:"Analyse urinaire. Diagnostic des infections et maladies rénales."},
    {code:"B2MI 2 HN",name:"*BETA 2 MICROGLOBULINE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:200.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"BILPH 3 HN",name:"*BILAN DES ANTIPHOSPHOLIPIDES",sector:"LIS",delay:"4 jours",price:1005.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"BRUC 0268",name:"*BRUCELLOSE SERODIAGNOSTIC",sector:"LIS",delay:"1 jour",price:60.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"C3  1 0348",name:"*C3C",sector:"LP",delay:"1 jour",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CALUR 0172",name:"*CALCUL URINAIRE SPECTRO INFRAROUGE",sector:"LELU",delay:"6 jours",price:220.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"TIBC 1 0116",name:"*CAPACITE DE FIXATION DU FER (TIBC)",sector:"LB",delay:"1 jour",price:100.00,description:"Fer sérique. Diagnostic des anémies ferriprives et surcharge en fer."},
    {code:"CLCR 2 0205",name:"*CLAIRENCE CREATININE",sector:"LB",delay:"3 jours",price:50.00,description:"Marqueur de la fonction rénale. Évalue la filtration glomérulaire et détecte l\'insuffisance rénale."},
    {code:"CORU HN",name:"*CORTISOL URINAIRE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:250.00,description:"Hormone du stress et du métabolisme. Diagnostic du syndrome de Cushing ou Addison."},
    {code:"CYFRA HN",name:"*CYFRA 21-1",sector:"LIC",delay:"A TELEPHONER",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*ABDI1 BP23",name:"BACTERIOLOGIE D’UN CATHETER",sector:"LBM",delay:"5 jours",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"ABDIV1 BP23",name:"BACTERIOLOGIE DIVERS",sector:"LBM",delay:"7 jours",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"BAC 0241",name:"BACTERIOLOGIE PREL.DIVERS",sector:"LBM",delay:"4 jours",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"BHCG 1 0150",name:"BETA-HCG PLASMATIQUE",sector:"LIC",delay:"1 jour",price:250.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"BHCGH 0150",name:"BETA-HCG PLASMATIQUE (HOMME)",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:250.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"BILD 2 HN",name:"BILIRUBINE DIRECTE/INDIRECTE",sector:"LB",delay:"1 jour",price:140.00,description:"Pigment jaune du sang. Évalue la fonction hépatique et diagnostic de l\'ictère (jaunisse)."},
    {code:"BILT 0103",name:"BILIRUBINE TOTALE",sector:"LB",delay:"1 jour",price:140.00,description:"Pigment jaune du sang. Évalue la fonction hépatique et diagnostic de l\'ictère (jaunisse)."},
    {code:"CA 125 0359",name:"CA125",sector:"LIC",delay:"1 jour",price:400.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CA153 0360",name:"CA15.3",sector:"LIC",delay:"1 jour",price:400.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CA199 0361",name:"CA19. 9",sector:"LIC",delay:"1 jour",price:400.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CA 0104",name:"CALCIUM (SANG)",sector:"LB",delay:"1 jour",price:30.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CACOR",name:"CALCIUM CORRIGE",sector:"LB",delay:"1 jour",price:90.00,description:"Immunoglobulines E. Diagnostic des allergies et maladies parasitaires."},
    {code:"CAI",name:"CALCIUM IONISE",sector:"LB",delay:"A TELEPHONER",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CALIR HN",name:"ANALYSE D’UN CALCUL (DIVERS)",sector:"LELU",delay:"7 jours",price:220.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CALUR TX31",name:"ANALYSE D’UN CALCUL URINAIRE",sector:"LELU",delay:"6 jours",price:220.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CALB TX32",name:"ANALYSE D’UN CALCUL BILIAIRE",sector:"LELU",delay:"6 jours",price:220.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CAU 0168",name:"CALCIUM URINAIRE",sector:"LB",delay:"2 jours",price:30.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CL 0105",name:"CHLORE (SANG)",sector:"LB",delay:"1 jour",price:30.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CLU 0169",name:"CHLORE URINAIRE",sector:"LB",delay:"2 jours",price:30.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CHOL 1 0106",name:"CHOLESTEROL",sector:"LB",delay:"1 jour",price:30.00,description:"Dosage du cholestérol total. Évaluation du risque cardiovasculaire et bilan lipidique complet."},
    {code:"HDLC 1 0108",name:"CHOLESTEROL HDL",sector:"LB",delay:"1 jour",price:30.00,description:"Dosage du cholestérol total. Évaluation du risque cardiovasculaire et bilan lipidique complet."},
    {code:"LDLC 3 0109",name:"CHOLESTEROL LDL",sector:"LB",delay:"1 jour",price:30.00,description:"Dosage du cholestérol total. Évaluation du risque cardiovasculaire et bilan lipidique complet."},
    {code:"LDLD 2 0109",name:"CHOLESTEROL LDL (DOSAGE)",sector:"LB",delay:"1 jour",price:30.00,description:"Dosage du cholestérol total. Évaluation du risque cardiovasculaire et bilan lipidique complet."},
    {code:"HLM 0207",name:"COMPTE D’ADDIS",sector:"LBM",delay:"1 jour",price:30.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*COP1 0255",name:"COPROCULTURE",sector:"LBM",delay:"4 jours",price:160.00,description:"Analyse bactériologique. Identification du germe responsable d\'infection."},
    {code:"CORT3 0153",name:"CORTISOL 16H",sector:"LIC",delay:"2 jours",price:250.00,description:"Hormone du stress et du métabolisme. Diagnostic du syndrome de Cushing ou Addison."},
    {code:"CORT23 0153",name:"CORTISOL 8H",sector:"LIC",delay:"1 jour",price:250.00,description:"Hormone du stress et du métabolisme. Diagnostic du syndrome de Cushing ou Addison."},
    {code:"*EXP1 0241",name:"CRACHATS GERMES BANALS (ECB)",sector:"LBM",delay:"3 jours",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CRE  1 0111",name:"CREATININE (SANG)",sector:"LB",delay:"1 jour",price:30.00,description:"Marqueur de la fonction rénale. Évalue la filtration glomérulaire et détecte l\'insuffisance rénale."},
    {code:"CK 0138",name:"CREATININE KINASE (C.K)",sector:"LB",delay:"1 jour",price:100.00,description:"Marqueur de la fonction rénale. Évalue la filtration glomérulaire et détecte l\'insuffisance rénale."},
    {code:"CREU 2 0170",name:"CREATININE URINAIRE",sector:"LB",delay:"2 jours",price:30.00,description:"Marqueur de la fonction rénale. Évalue la filtration glomérulaire et détecte l\'insuffisance rénale."},
    {code:"CGLY 1 HN",name:"CYCLE GLYCEMIQUE",sector:"LB",delay:"2 jours",price:240.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*BAC1 0241",name:"CYTOBACTERIOLOGIE DIVERS",sector:"LBM",delay:"7 jours",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*PUSF1 0241",name:"CYTOBACTERIOLOGIE DE PUS « FERME »",sector:"LBM",delay:"7 jours",price:150.00,description:"Fer sérique. Diagnostic des anémies ferriprives et surcharge en fer."},
    {code:"* PUS  1 0241",name:"CYTOBACTERIOLOGIE PUS SUPERFICIEL",sector:"LBM",delay:"4 jours",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*URET1 0241",name:"CYTOBACTERIOLOGIE (HOMME)",sector:"LBM",delay:"4 jours",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*VAG1 0241",name:"CYTOBACTERIOLOGIE (GENITAL FEMME)",sector:"LBM",delay:"4 jours",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*VULV1 0241",name:"CYTOBACTERIOLOGIE (VULVAIRE)",sector:"LBM",delay:"4 jours",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*ŒIL 1 0241",name:"CYTOBACTERIOLOGIE CONJONCTIVAL DROIT",sector:"LBM",delay:"4 jours",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*ŒIL6S 0241",name:"CYTOBACTERIOLOGIE CONJONCTIVAL GAUCHE",sector:"LBM",delay:"4 jours",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*OREI1 0241",name:"CYTOBACTERIOLOGIEOREILLE",sector:"LBM",delay:"4 jours",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*GORG1 0241",name:"CYTOBACTERIOLOGIE BOUCHE & GORGE",sector:"LBM",delay:"3 jours",price:90.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CRIS HN",name:"*CRISTALLURIE",sector:"LELU",delay:"7 jours",price:220.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CRISA HN",name:"*CRISTAUX LIQUIDE ARTICULAIRE",sector:"LELU",delay:"1 jour",price:60.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CALB HN",name:"*CALCUL BILIAIRE : SPECTRO INFRAROUGE",sector:"LELU",delay:"7 jours",price:220.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CD 0224",name:"*COOMBS DIRECT",sector:"LH",delay:"2 jours",price:60.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CKMB 0139",name:"*CK-MB(CREATININE KINASE MB)",sector:"LIC",delay:"1 jour",price:200.00,description:"Marqueur de la fonction rénale. Évalue la filtration glomérulaire et détecte l\'insuffisance rénale."},
    {code:"CICLO TX11",name:"CICLOSPORINE",sector:"LSM",delay:"10 jours",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"GUANS",name:"GUANIDOINOACETATE(Sang)",sector:"LSM",delay:"A TELEPHONER",price:700.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"GUANU",name:"GUANIDOINOACETATE(Urine)",sector:"LSM",delay:"A TELEPHONER",price:700.00,description:"Analyse urinaire. Diagnostic des infections et maladies rénales."},
    {code:"AOR",name:"ACIDE OROTIQUE(Urine)",sector:"LSM",delay:"A TELEPHONER",price:360.00,description:"Analyse urinaire. Diagnostic des infections et maladies rénales."},
    {code:"CRTIU",name:"CREATINE(Urine)",sector:"LSM",delay:"A TELEPHONER",price:350.00,description:"Analyse urinaire. Diagnostic des infections et maladies rénales."},
    {code:"CRTIS",name:"CREATINE(Sang)",sector:"LSM",delay:"A TELEPHONER",price:350.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CARBA TX09",name:"CARBAMAZEPINE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CYS",name:"Cystine urinaire",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:350.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CU",name:"CUPREMIE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CUU",name:"CUPREURIE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CER",name:"CERULEOPLASMIN",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:120.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CHPNE",name:"CHLAMYDOPHILIA PNEUMONIAE",sector:"DBS",delay:"5 jours",price:450.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CRYO HN",name:"*CRYOGLOBULINE",sector:"LP",delay:"7 jours",price:70.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CRP 0367",name:"*CRP (PROTEINE C REACTIVE)",sector:"LP",delay:"1 jour",price:100.00,description:"C-réactive protéine. Marqueur sensible de l\'inflammation aiguë et des infections."},
    {code:"COPF 0258",name:"*COPROLOGIE FONCTIONNELLE",sector:"LPM",delay:"1 jour",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"COPF2 0258",name:"*COPROLOGIE FONCTIONNELLE",sector:"LPM",delay:"1 jour",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CARBA HN",name:"*CARBAMAZEPINE (SANG)",sector:"Labo. Spécialisé",delay:"10 jours",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CANNA HN",name:"*CANNABIS",sector:"DTP",delay:"1 jour",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"COCA HN",name:"*COCAINE",sector:"DTP",delay:"1 jour",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"BKPCR HN",name:"IDENTIFICATION MOLECULAIRE DES MYCOBACTERIES",sector:"DBS",delay:"7 jours",price:900.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"BKPCR2",name:"*PCR MYCOBACTERIES",sector:"DBS",delay:"7 jours",price:900.00,description:"Détection par biologie moléculaire. Test très sensible pour diagnostic d\'infection."},
    {code:"BKSEQ HN",name:"IDENTIFICATION DES MYCOBACTERIES ATYPIQUES PAR SEQUENCAGE",sector:"DBS",delay:"10 jours",price:950.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"KGBXP HN",name:"DETECTION DIRECT MTB/RIF",sector:"DBS",delay:"2 jours",price:900.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"DHT HN",name:"*DEHYDROTESTOSTERONE(DHT)",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:200.00,description:"Hormone masculine principale. Évalue la fonction testiculaire, fertilité et virilisation."},
    {code:"SDHEA HN",name:"*DEHYDROEPIANDROSTERONE SULFATE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:400.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"DELT4 0405",name:"*DELTA 4 ANDROSTENEDIONE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:400.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"DENSU HN",name:"*DENSITE URINAIRE",sector:"LELU",delay:"1 jour",price:20.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"DOPA HN",name:"*DOPAMINE (URINE 24H)",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:700.00,description:"Analyse urinaire. Diagnostic des infections et maladies rénales."},
    {code:"D2 HN",name:"*DERMAT FARINAE",sector:"LIS",delay:"4 jours",price:180.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"D1 0352",name:"*DERMAT PTERONYSSINUS",sector:"LIS",delay:"4 jours",price:180.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"DD XX01",name:"*D-DIMER",sector:"LIC",delay:"1 jour",price:200.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"DEPIS HN",name:"*DEPISTAGE DROGUES URINES",sector:"DTP",delay:"1 jour",price:700.00,description:"Analyse urinaire. Diagnostic des infections et maladies rénales."},
    {code:"AH1N1 HN",name:"*DETECTION DU VIRUS A/(H1N1)",sector:"DBS",delay:"1 jour",price:1000.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CORON",name:"DETECTION DE CORONAVIRUS (HCOV-EMC)",sector:"DBS",delay:"1 jour",price:1000.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"DLL XX10",name:"*DOSAGE DES CHAINES LEGERES LIBRES",sector:"LP",delay:"7 jours",price:500.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CALP HN",name:"*DOSAGE DE LA CALPROTECTINE FECALE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:750.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"ANGIO 0410",name:"*ENZYME CV ANGIOTENSINE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:400.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*ECBU3 0241",name:"ECBU : EXAMEN BACTERIOLOGIQUE",sector:"LBM",delay:"3 jours",price:150.00,description:"Examen cytobactériologique des urines. Diagnostic des infections urinaires."},
    {code:"E2  1 0152",name:"ESTRADIOL (E2)",sector:"LIC",delay:"1 jour",price:250.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"EHBAC 0112",name:"*ELECTRO HEMOGLOBINE (PH ACIDE)",sector:"LP",delay:"7 jours",price:100.00,description:"Protéine transportant l\'oxygène. Diagnostic des anémies."},
    {code:"EHBAL1 0112",name:"*ELECTRO D’ HEMOGLOBINE (PH ALCALIN)",sector:"LP",delay:"7 jours",price:100.00,description:"Protéine transportant l\'oxygène. Diagnostic des anémies."},
    {code:"HBCL HN",name:"*ETUDES DES HEMOGLOBINES PAR HPLC",sector:"LP",delay:"7 jours",price:200.00,description:"Protéine transportant l\'oxygène. Diagnostic des anémies."},
    {code:"EPP 2 0114",name:"ELECTROPHORESE DES PROT. SERIQUES",sector:"LP",delay:"3 jours",price:100.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"PARA1 0254",name:"*EXAMEN PARASITOLOGIQUE DES SELLES (J1)",sector:"LPM",delay:"1 jour",price:120.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"FT  1 HN",name:"*FIBROTEST-ACTITEST",sector:"LB/LP",delay:"2 jours",price:800.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"FM HN",name:"*FIBROMAX",sector:"LB/LP",delay:"2 jours",price:1350.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"FE 0115",name:"FER SERIQUE",sector:"LB",delay:"1 jour",price:60.00,description:"Fer sérique. Diagnostic des anémies ferriprives et surcharge en fer."},
    {code:"FRUC HN",name:"FRUCTOSAMINE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:80.00,description:"Reflet de la glycémie sur 2-3 semaines. Alternative à l\'HbA1c."},
    {code:"F2  1 0231",name:"*FACTEUR DE LA COAGULATION II",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:75.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"F5  1 0231",name:"*FACTEUR DE LA COAGULATION V",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:75.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"F7  1 0231",name:"*FACTEUR DE LA COAGULATION VII",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:75.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"F10  1 0231",name:"*FACTEUR DE LA COAGULATION X",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:75.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"F11  1 0231",name:"*FACTEUR DE LA COAGULATION XI",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:75.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"F12  1 0231",name:"*FACTEUR DE LA COAGULATION XII",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:75.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"F8  1 0232",name:"*FACTEUR DE LA COAGULATION VIII",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:75.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"F9  1 0232",name:"*FACTEUR DE LA COAGULATION IX",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:75.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"FT4 0161",name:"FT4 (THYROXINE LIBRE)",sector:"LIC",delay:"1 jour",price:200.00,description:"Thyroxine. Principale hormone thyroïdienne. Diagnostic des pathologies thyroïdiennes."},
    {code:"FSH HN",name:"F.S.H (HORMONE FOLLICULOSTIMULANTE)",sector:"LIC",delay:"1 jour",price:250.00,description:"Dosage hormonal. Évalue le fonctionnement du système endocrinien et la fertilité."},
    {code:"FT3 0165",name:"FT3 (TRIODOTHYRONINE LIBRE)",sector:"LIC",delay:"1 jour",price:300.00,description:"Triiodothyronine. Hormone thyroïdienne active. Évalue l\'hyperthyroïdie."},
    {code:"FERR 0154",name:"FERRITINE",sector:"LIC",delay:"1 jour",price:250.00,description:"Fer sérique. Diagnostic des anémies ferriprives et surcharge en fer."},
    {code:"FR",name:"*FACTEUR RHUMATOIDE",sector:"LIS",delay:"4 jours",price:150.00,description:"Auto-anticorps. Diagnostic de la polyarthrite rhumatoïde."},
    {code:"G6PD",name:"*G6PD ERYTHROCYTAIRE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:100.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"GENHC HN",name:"*GENOTYPAGE HCV",sector:"LBMM",delay:"A TELEPHONER",price:1200.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"GLUR 0180",name:"*GLUCOSE URINE RECHERCHE",sector:"LB",delay:"1 jour",price:10.00,description:"Analyse urinaire. Diagnostic des infections et maladies rénales."},
    {code:"GLUD 1 0181",name:"GLUCOSE URINE DOSAGE",sector:"LB",delay:"1 jour",price:30.00,description:"Analyse urinaire. Diagnostic des infections et maladies rénales."},
    {code:"GLY1 0118",name:"GLYCEMIE A JEUN",sector:"LB",delay:"1 jour",price:30.00,description:"Mesure du taux de sucre dans le sang. Essentiel pour le diagnostic et suivi du diabète. À jeun ou post-prandial."},
    {code:"GLY2",name:"GLYCEMIEP2",sector:"LB",delay:"1 jour",price:30.00,description:"Mesure du taux de sucre dans le sang. Essentiel pour le diagnostic et suivi du diabète. À jeun ou post-prandial."},
    {code:"GLY3",name:"GLYCEMIEP3",sector:"LB",delay:"1 jour",price:30.00,description:"Mesure du taux de sucre dans le sang. Essentiel pour le diagnostic et suivi du diabète. À jeun ou post-prandial."},
    {code:"GLYG",name:"GLYCEMIE A JEUN GROSSESSE",sector:"LB",delay:"1 jour",price:30.00,description:"Mesure du taux de sucre dans le sang. Essentiel pour le diagnostic et suivi du diabète. À jeun ou post-prandial."},
    {code:"GLYH",name:"GLYCEMIE A JEUN HORS LABO",sector:"LB",delay:"1 jour",price:30.00,description:"Mesure du taux de sucre dans le sang. Essentiel pour le diagnostic et suivi du diabète. À jeun ou post-prandial."},
    {code:"GLYPC 0118",name:"GLYCEMIE POST CHARGE",sector:"LB",delay:"1 jour",price:30.00,description:"Mesure du taux de sucre dans le sang. Essentiel pour le diagnostic et suivi du diabète. À jeun ou post-prandial."},
    {code:"GLYPP1 0118",name:"GLYCEMIE POST PRANDIALE",sector:"LB",delay:"2 jours",price:60.00,description:"Mesure du taux de sucre dans le sang. Essentiel pour le diagnostic et suivi du diabète. À jeun ou post-prandial."},
    {code:"GGT 0141",name:"GAMMA-GT (GGT)",sector:"LB",delay:"1 jour",price:50.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"GR 0229",name:"GROUPAGE ABO",sector:"LH",delay:"2 jours",price:160.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"GEP 0213",name:"*GOUTTE EPAISSE RECHERCHE PLASMODIUM",sector:"LPM",delay:"2 jours",price:54.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"5HIA 0183",name:"*5 HIA SUR URINES DE 24H",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:27.00,description:"Analyse urinaire. Diagnostic des infections et maladies rénales."},
    {code:"HGPG 0206",name:"*HGPO SUR GH",sector:"LB/LIC",delay:"2 jours",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"HGPO 0206",name:"HYPERGLYCEMIE",sector:"LB",delay:"2 jours",price:150.00,description:"Mesure du taux de sucre dans le sang. Essentiel pour le diagnostic et suivi du diabète. À jeun ou post-prandial."},
    {code:"HGPO3 0206",name:"HYPERGLYCEMIE SUR 3 HEURES",sector:"LB",delay:"2 jours",price:150.00,description:"Mesure du taux de sucre dans le sang. Essentiel pour le diagnostic et suivi du diabète. À jeun ou post-prandial."},
    {code:"HGPO5 0206",name:"HYPERGLYCEMIE SUR 5 HEURES",sector:"LB",delay:"2 jours",price:150.00,description:"Mesure du taux de sucre dans le sang. Essentiel pour le diagnostic et suivi du diabète. À jeun ou post-prandial."},
    {code:"*HEMO1 0250",name:"*HEMOCULTURE",sector:"LBM",delay:"2 jours",price:337.00,description:"Analyse bactériologique. Identification du germe responsable d\'infection."},
    {code:"25D 1 0381",name:"*25 HYDROXY VITAMINE D",sector:"LC",delay:"2 jours",price:460.00,description:"Vitamine essentielle pour les os et l\'immunité. Dépistage de la carence très fréquente."},
    {code:"HYDA 0294",name:"*HYDATIDOSE SERODIAGNOSTIC",sector:"LIS",delay:"1 jour",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"HIV 1 0327",name:"HIV1+2 ANTICORPS +P24",sector:"LIS",delay:"1 jour",price:200.00,description:"Sérologie VIH. Dépistage du virus de l\'immunodéficience humaine (SIDA)."},
    {code:"GH0 0415",name:"*HORMONE DE CROISSANCE TO",sector:"LIC",delay:"1 jour",price:400.00,description:"Dosage hormonal. Évalue le fonctionnement du système endocrinien et la fertilité."},
    {code:"GH-15 0415",name:"*HORMONE DE CROISSANCE T15",sector:"LIC",delay:"1 jour",price:400.00,description:"Dosage hormonal. Évalue le fonctionnement du système endocrinien et la fertilité."},
    {code:"GH-30 0415",name:"*HORMONE DE CROISSANCE T30",sector:"LIC",delay:"1 jour",price:400.00,description:"Triiodothyronine. Hormone thyroïdienne active. Évalue l\'hyperthyroïdie."},
    {code:"GH45 0415",name:"*HORMONE DE CROISSANCE T45",sector:"LIC",delay:"1 jour",price:400.00,description:"Thyroxine. Principale hormone thyroïdienne. Diagnostic des pathologies thyroïdiennes."},
    {code:"GH60 0415",name:"*HORMONE DE CROISSANCE T60",sector:"LIC",delay:"1 jour",price:400.00,description:"Dosage hormonal. Évalue le fonctionnement du système endocrinien et la fertilité."},
    {code:"GH75 0415",name:"*HORMONE DE CROISSANCE T75",sector:"LIC",delay:"1 jour",price:400.00,description:"Dosage hormonal. Évalue le fonctionnement du système endocrinien et la fertilité."},
    {code:"GH90 0415",name:"*HORMONE DE CROISSANCE T90",sector:"LIC",delay:"1 jour",price:400.00,description:"Dosage hormonal. Évalue le fonctionnement du système endocrinien et la fertilité."},
    {code:"GH150 0415",name:"*HORMONE DE CROISSANCE T150",sector:"LIC",delay:"1 jour",price:400.00,description:"Dosage hormonal. Évalue le fonctionnement du système endocrinien et la fertilité."},
    {code:"GH180 0415",name:"*HORMONE DE CROISSANCE T180",sector:"LIC",delay:"1 jour",price:400.00,description:"Dosage hormonal. Évalue le fonctionnement du système endocrinien et la fertilité."},
    {code:"HBA1C 0119",name:"*HEMOGLOBINE A1C",sector:"LP",delay:"1 jour",price:100.00,description:"Protéine transportant l\'oxygène. Diagnostic des anémies."},
    {code:"HAPTO1 0368",name:"*HAPTOGLOBINE",sector:"LP",delay:"1 jour",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"IGETC 0351",name:"*IGE TOTALES",sector:"LIS",delay:"4 jours",price:200.00,description:"Immunoglobulines E. Diagnostic des allergies et maladies parasitaires."},
    {code:"IFNGQ XX18",name:"*INTERFERON GAMMA QUANTIFERON",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:800.00,description:"Fer sérique. Diagnostic des anémies ferriprives et surcharge en fer."},
    {code:"IGF1",name:"*IGF1",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:400.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"INS 0155",name:"INSULINE",sector:"LIC",delay:"1 jour",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"AMH",name:"HORMONE ANTI-MULLERIENNE",sector:"LIC",delay:"3 jours",price:500.00,description:"Dosage hormonal. Évalue le fonctionnement du système endocrinien et la fertilité."},
    {code:"INHIB",name:"INHIBINE B",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:500.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"HPV",name:"HPV  CAVITE BUCCALE",sector:"DBS",delay:"A TELEPHONER",price:1000.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"HPVEC",name:"*DIAGNOSTIC HPV  ENDOCERVICAL",sector:"DBS",delay:"A TELEPHONER",price:1000.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"INS1 0155",name:"INSULINE",sector:"LIC",delay:"1 jour",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"INS2 0155",name:"INSULINE",sector:"LIC",delay:"1 jour",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"INS3 0155",name:"INSULINE",sector:"LIC",delay:"1 jour",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"INS4 0155",name:"INSULINE",sector:"LIC",delay:"1 jour",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"INS5 0155",name:"INSULINE",sector:"LIC",delay:"1 jour",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"INS6 0155",name:"INSULINE",sector:"LIC",delay:"1 jour",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"INS7 0155",name:"INSULINE",sector:"LIC",delay:"1 jour",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"INS8 0155",name:"INSULINE",sector:"LIC",delay:"1 jour",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"INS9 0155",name:"INSULINE",sector:"LIC",delay:"1 jour",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"INS10 0155",name:"INSULINE",sector:"LIC",delay:"1 jour",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CHLAS 1",name:"IGG CHLAMYDIA SERODIAGNOSTIC",sector:"LIS",delay:"7 jours",price:180.00,description:"Détection de Chlamydia trachomatis. IST fréquente causant stérilité."},
    {code:"IGA 1 0373",name:"*IGA",sector:"LP",delay:"1 jour",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"IGG 1 0372",name:"*IGG",sector:"LP",delay:"1 jour",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"IGM 1 0374",name:"*IGM",sector:"LP",delay:"1 jour",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"IFIXU HN",name:"*IMMUNOFIXATION URINE",sector:"LP",delay:"7 jours",price:600.00,description:"Analyse urinaire. Diagnostic des infections et maladies rénales."},
    {code:"IT 0355",name:"*IMMUNOFIXATION SANG",sector:"LP",delay:"3 jours",price:600.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"IMLA",name:"*IMMUNOPHENOTYPAGE LEUCEMIE AIGUE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:1200.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"IMLY",name:"*IMMUNOPHENOTYPAGE LYMPHOCYTAIRE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:1200.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"IONOC HN",name:"IONOGRAMME COMPLET",sector:"LB",delay:"1 jour",price:250.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"IONO HN",name:"IONOGRAMME",sector:"LB",delay:"1 jour",price:160.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"IONOU HN",name:"IONOGRAMME URINAIRE",sector:"LB",delay:"2 jours",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"LDH1 0142",name:"L.D.H",sector:"LB",delay:"1 jour",price:50.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"LIPA 0148",name:"LIPASE",sector:"LB",delay:"1 jour",price:100.00,description:"Enzyme pancréatique. Marqueur spécifique des pancréatites."},
    {code:"*LART1 0241",name:"LIQUIDE ARTICULAIRE",sector:"LBM",delay:"4 jours",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*LASC1 0241",name:"LIQUIDE D’ASCITE (ECB)",sector:"LBM",delay:"3 jours",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*LCR 1 0241",name:"LCR (ECB)",sector:"LBM",delay:"3 jours",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*LPLE 1 0241",name:"LIQUIDE PLEURAL",sector:"LBM",delay:"3 jours",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*LPLE 0241",name:"LIQUIDE PLEURAL (ECB)",sector:"LBM",delay:"4 jours",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"LH 0156",name:"LH (HORMONE LUTEINISANTE)",sector:"LIC",delay:"1 jour",price:250.00,description:"Dosage hormonal. Évalue le fonctionnement du système endocrinien et la fertilité."},
    {code:"MGERY 0127",name:"*MAGNESIUM ERYTHROCYTAIRE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:80.00,description:"Magnésium sanguin. Diagnostic des crampes, fatigue et troubles du rythme cardiaque."},
    {code:"MGSE2 0126",name:"*MAGNESIUM SERIQUE",sector:"LB",delay:"1 jour",price:60.00,description:"Magnésium sanguin. Diagnostic des crampes, fatigue et troubles du rythme cardiaque."},
    {code:"MGU",name:"*MAGNESIUM URINAIRE",sector:"LB",delay:"2 jours",price:30.00,description:"Magnésium sanguin. Diagnostic des crampes, fatigue et troubles du rythme cardiaque."},
    {code:"MYCOD1 0247",name:"MYCOLOGIE DIVERS",sector:"LBM",delay:"2 jours",price:101.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*MYBOS 0247",name:"MYCOLOGIE BUCCO-LUNGUAL",sector:"LBM",delay:"5 jours",price:301.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*MYMS1 0247",name:"MYCOLOGIE ONGLES MAIN DROIT",sector:"LBM",delay:"2 jours",price:301.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*MYMS2 0247",name:"MYCOLOGIE ONGLES MAIN GAUCHE",sector:"LBM",delay:"2 jours",price:301.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"MYP2S1 0247",name:"MYCOLOGIE ONGLES PIED DROIT",sector:"LBM",delay:"2 jours",price:101.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"MYP3S1 0247",name:"MYCOLOGIE ONGLES PIED GAUCHE",sector:"LBM",delay:"2 jours",price:101.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"MYPES1 0247",name:"MYCOLOGIE(PEAU)",sector:"LBM",delay:"2 jours",price:101.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*MYQM1 0247",name:"MYCOLOGIE SQUAMES MAIN DROIT",sector:"LBM",delay:"2 jours",price:301.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*MYQM2 0247",name:"MYCOLOGIE SQUAMES MAIN GAUCHE",sector:"LBM",delay:"2 jours",price:301.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"MYQPS2",name:"MYCOLOGIE SQUAMES PIED DROIT",sector:"LBM",delay:"2 jours",price:101.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"MYQPS1",name:"MYCOLOGIE SQUAMES PIED GAUCHE",sector:"LBM",delay:"2 jours",price:101.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"MYPNE",name:"MYCOPLASMA PNEUMONIAE",sector:"DBS",delay:"5 jours",price:450.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"MYCP1 0253",name:"RECHERCHE DES MYCOPLASMES",sector:"LBM",delay:"4 jours",price:200.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"MYCOP 2 0253",name:"RECHERCHE DES MYCOPLASMES (2ème site de prélèvement)",sector:"LBM",delay:"4 jours",price:200.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CTXPR",name:"RECHERCHE DE CHLAMYDIA TRACHOMATIS PAR AMPLIFICATION MOLECULAIRE",sector:"DBS",delay:"5 jours",price:450.00,description:"Détection de Chlamydia trachomatis. IST fréquente causant stérilité."},
    {code:"HPVCO",name:"RECHERCHES ET TYPAGE DES HPV ONCOGENES",sector:"DBS",delay:"15 jours",price:1000.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"MEDU1 0218",name:"*MEDULOGRAMME",sector:"LH",delay:"3 jours",price:120.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"MNI 0330",name:"*MONONUCLEOSE INFECT SERO (MNI TEST)",sector:"LIS",delay:"1 jour",price:50.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"NSE 0364",name:"*(NSE) NEURON SPECIFIC ENOLASE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:400.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"N FS 0216",name:"NFS NUMERATION FORMULE SANGUINE",sector:"LH",delay:"1 jour",price:110.00,description:"Numération formule sanguine complète. Analyse des globules rouges, blancs et plaquettes."},
    {code:"NMETT 0188",name:"*NORMETANEPHRINE URINAIRE URINE DE 24H",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:250.00,description:"Analyse urinaire. Diagnostic des infections et maladies rénales."},
    {code:"NORAT HN",name:"*NORADRENALINE URINE DE 24H",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:500.00,description:"Analyse urinaire. Diagnostic des infections et maladies rénales."},
    {code:"PBNP HN",name:"*NT-PRO BNP",sector:"LIC",delay:"1 jour",price:400.00,description:"Peptide natriurétique. Diagnostic et suivi de l\'insuffisance cardiaque."},
    {code:"OXAL1 0128",name:"OXALATES URINAIRES",sector:"LELU",delay:"7 jours",price:180.00,description:"Enzyme hépatique (GPT/ALT). Marqueur sensible de lésion des cellules du foie. Augmentée en hépatite."},
    {code:"ORO 2 0369",name:"*OROSOMUCOIDE ALPHA1 GLYCOPROTEINE A",sector:"LP",delay:"1 jour",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"OPIUM HN",name:"*OPIACES(URINE)",sector:"DTP",delay:"1 jour",price:300.00,description:"Analyse urinaire. Diagnostic des infections et maladies rénales."},
    {code:"PROTC HN",name:"*PROTEINE C",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:200.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"PROTS HN",name:"*PROTEINE S",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:200.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"PEPTC 0426",name:"*PEPTIDE C",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:400.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"PHU 0173",name:"*PH URINAIRE",sector:"LB",delay:"1 jour",price:10.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"PROUR 0176",name:"*PROTEINE URINE RECHERCHE",sector:"LB",delay:"1 jour",price:20.00,description:"Analyse urinaire. Diagnostic des infections et maladies rénales."},
    {code:"K 0131",name:"POTASSIUM(SANG)",sector:"LB",delay:"1 jour",price:30.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"KU 0175",name:"POTASSIUM URINAIRE",sector:"LB",delay:"2 jours",price:30.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"PROTU 0177",name:"PROTEINES URINAIRES(DOSAGE)",sector:"LB",delay:"2 jours",price:30.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"PT 0130",name:"PROTEINES(SANG)",sector:"LB",delay:"1 jour",price:30.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"P 0129",name:"PHOSPHORE(SANG)",sector:"LB",delay:"1 jour",price:40.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"PU 0174",name:"PHOSPHORE(URINE)",sector:"LB",delay:"2 jours",price:40.00,description:"Analyse urinaire. Diagnostic des infections et maladies rénales."},
    {code:"PAL 1 0143",name:"PHOSPHATASES ALCALINES(PAL)",sector:"LB",delay:"1 jour",price:50.00,description:"Phosphatases alcalines. Évalue les atteintes hépatiques, osseuses et biliaires."},
    {code:"HBPQT 0321",name:"*PCR HBV (CHARGE VIRALE)",sector:"LBMM",delay:"4 jours",price:600.00,description:"Détection par biologie moléculaire. Test très sensible pour diagnostic d\'infection."},
    {code:"HCVGX 0324",name:"*PCR HCV (CHARGE VIRALE)",sector:"LBMM",delay:"7 jours",price:900.00,description:"Détection par biologie moléculaire. Test très sensible pour diagnostic d\'infection."},
    {code:"PLQ 0217",name:"PLAQUETTES",sector:"LH",delay:"1 jour",price:30.00,description:"Cellules de la coagulation. Évalue les risques hémorragiques et thrombotiques."},
    {code:"PLQC 0217",name:"PLAQUETTES",sector:"LH",delay:"1 jour",price:30.00,description:"Cellules de la coagulation. Évalue les risques hémorragiques et thrombotiques."},
    {code:"PRL 0158",name:"PROLACTINE A T0",sector:"LIC",delay:"1 jour",price:250.00,description:"Hormone lactogène. Diagnostic des troubles menstruels, galactorrhée et infertilité."},
    {code:"PRL2 0158",name:"PROLACTINE (P.R.L) T20",sector:"LIC",delay:"1 jour",price:250.00,description:"Hormone lactogène. Diagnostic des troubles menstruels, galactorrhée et infertilité."},
    {code:"PROG 0157",name:"PROGESTERONE",sector:"LIC",delay:"1 jour",price:250.00,description:"Hormone de la grossesse. Évalue l\'ovulation et suivi de début de grossesse."},
    {code:"PTH 0425",name:"PTH (PARATHORMONE INTACT 1-84)",sector:"LIC",delay:"1 jour",price:300.00,description:"Dosage hormonal. Évalue le fonctionnement du système endocrinien et la fertilité."},
    {code:"PCT HN",name:"*PROCALCITONINE",sector:"LIC",delay:"1 jour",price:400.00,description:"Marqueur spécifique d\'infection bactérienne sévère. Guide l\'antibiothérapie."},
    {code:"PSAT 1 0358",name:"P.S.A (ANTIGENE SPECIFIQUE PROSTATE)",sector:"LIC",delay:"1 jour",price:300.00,description:"Antigène prostatique spécifique. Dépistage et suivi du cancer de la prostate chez l\'homme."},
    {code:"PSALI1 HN",name:"P.S.A LIBRE /P.S.A TOTAL",sector:"LIC",delay:"1 jour",price:300.00,description:"Antigène prostatique spécifique. Dépistage et suivi du cancer de la prostate chez l\'homme."},
    {code:"PBJ HN",name:"*PROTEINES DE BENCE-JONES",sector:"LP",delay:"7 jours",price:600.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"RA 0132",name:"RESERVE ALCALINE(TCO2)",sector:"LB",delay:"1 jour",price:40.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"RAPPC",name:"RAPPORT PROTEINE/CREATININE URINAIRE",sector:"LB",delay:"1 jour",price:60.00,description:"Marqueur de la fonction rénale. Évalue la filtration glomérulaire et détecte l\'insuffisance rénale."},
    {code:"RAPAC",name:"RAPPORT ALBUMINE/CREATININE URINAIRE",sector:"LB",delay:"1 jour",price:150.00,description:"Marqueur de la fonction rénale. Évalue la filtration glomérulaire et détecte l\'insuffisance rénale."},
    {code:"RST",name:"RECEPTEUR SOLUBLE DE LA TRANSFERINE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:220.00,description:"Fer sérique. Diagnostic des anémies ferriprives et surcharge en fer."},
    {code:"RETIC 0222",name:"RETICULOCYTES",sector:"LH",delay:"1 jour",price:30.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"RUBM 0341",name:"RUBEOLE SERODIAGNOSTIC (IGM)",sector:"LIS",delay:"1 jour",price:400.00,description:"Sérologie rubéole. Bilan pré-conceptionnel et surveillance de grossesse."},
    {code:"RUBG 0340",name:"RUBEOLE SERODIAGNOSTIC (IGG)",sector:"LIS",delay:"1 jour",price:150.00,description:"Sérologie rubéole. Bilan pré-conceptionnel et surveillance de grossesse."},
    {code:"RUBA HN",name:"RUBEOLE G AVIDITE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:800.00,description:"Sérologie rubéole. Bilan pré-conceptionnel et surveillance de grossesse."},
    {code:"DEMO",name:"PARASITOLOGIE DIVERS",sector:"LPM",delay:"1 jour",price:40.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"LEISH PA02",name:"* RECHERCHE DE LEISHMANIOSE",sector:"LPM",delay:"1 jour",price:27.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"RPARA PA10",name:"* RECHERCHE DE PARASITE F",sector:"LPM",delay:"2 jours",price:27.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"BILH HN",name:"*RECHERCHE ŒUFS BILHARZIE URINAIRE",sector:"LPM",delay:"1 jour",price:150.00,description:"Dosage hormonal. Évalue le fonctionnement du système endocrinien et la fertilité."},
    {code:"TCM 0213",name:"*RECHERCHE DES PLASMODIUM",sector:"LPM",delay:"1 jour",price:27.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"SARCO XX28",name:"*RECHERCHE DE SARCOPTE SCABEI",sector:"LPM",delay:"1 jour",price:60.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"SGI 0257",name:"*RECHERCHE DE SANG IMMUNOLO (SELLE)",sector:"LPM",delay:"1 jour",price:150.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"FILAR",name:"*RECHERCHE DE FILARIOSE",sector:"LPM",delay:"2 jours",price:200.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"EOSI HN",name:"RECHERCHE D’EOSINOPHILES (NEZ)",sector:"LH",delay:"1 jour",price:34.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"ROTA 0259",name:"RECHERCHE DE ROTAVIRUS (SELLES)",sector:"LBM",delay:"1 jour",price:200.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"ADENO 0260",name:"RECHERCHE D’ADENOVIRUS (SELLES)",sector:"LBM",delay:"1J",price:200.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"NA 0133",name:"SODIUM (SANG)",sector:"LB",delay:"1 jour",price:30.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"NAU 0179",name:"SODIUM URINAIRE",sector:"LB",delay:"2 jours",price:30.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"SGU 1 HN",name:"SANG DANS LES URINES",sector:"LB",delay:"1 jour",price:60.00,description:"Analyse urinaire. Diagnostic des infections et maladies rénales."},
    {code:"SPMO 0376",name:"*SPERMOGRAMME",sector:"LBM",delay:"2 jours",price:250.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"*SPCU1 0241",name:"*SPERMOCULTURE",sector:"LBM",delay:"7 jours",price:150.00,description:"Analyse bactériologique. Identification du germe responsable d\'infection."},
    {code:"AGHBS 0315",name:"SEROLOGIE HEPATITE B-AG HBS",sector:"LIS",delay:"1 jour",price:120.00,description:"Sérologie hépatite B. Dépistage et diagnostic de l\'infection virale hépatique B."},
    {code:"AGHBE 0317",name:"SEROLOGIE HEPATITE B AG-HBE",sector:"LIS",delay:"1 jour",price:250.00,description:"Sérologie hépatite B. Dépistage et diagnostic de l\'infection virale hépatique B."},
    {code:"HAM 0440",name:"SEROLOGIE HEPATITE A (IGM)",sector:"LIS",delay:"1 jour",price:250.00,description:"Test sérologique. Détection d\'anticorps pour diagnostic d\'infection."},
    {code:"HBC 0319",name:"SEROLOGIE HEPATITE B-AC HBC (IGG)",sector:"LIS",delay:"1 jour",price:250.00,description:"Sérologie hépatite B. Dépistage et diagnostic de l\'infection virale hépatique B."},
    {code:"HBCM HO22",name:"SEROLOGIE HEPATITE B-AC HBC (IGM)",sector:"LIS",delay:"1 jour",price:300.00,description:"Sérologie hépatite B. Dépistage et diagnostic de l\'infection virale hépatique B."},
    {code:"HBE 0318",name:"SEROLOGIE HEPATITE B-AC HBE",sector:"LIS",delay:"1 jour",price:250.00,description:"Sérologie hépatite B. Dépistage et diagnostic de l\'infection virale hépatique B."},
    {code:"HBS 0316",name:"SEROLOGIE HEPATITE B-AC HBS",sector:"LIS",delay:"1 jour",price:250.00,description:"Sérologie hépatite B. Dépistage et diagnostic de l\'infection virale hépatique B."},
    {code:"HCA 0322",name:"SEROLOGIE HEPATITE C",sector:"LIS",delay:"1 jour",price:300.00,description:"Sérologie hépatite C. Dépistage de l\'infection chronique du foie."},
    {code:"SPANC",name:"SPECIFICITE DES ANCA AC ANTI MPO/ANTI-PR3",sector:"LIS",delay:"4 jours",price:400.00,description:"Recherche d\'anticorps. Diagnostic des maladies auto-immunes ou infectieuses."},
    {code:"SCTAN 0261",name:"*SCOTCH TEST ANAL",sector:"LPM",delay:"1 jour",price:20.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"SCTCU1 HN",name:"*SCOTCH TEST CUTANE",sector:"LBM",delay:"2 jours",price:20.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"SCTCU2 HN",name:"*SCOTCH TEST CUTANE 2ème site",sector:"LBM",delay:"3 jours",price:20.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"LYMS",name:"*SEROLOGIE DE LYME",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:250.00,description:"Test sérologique. Détection d\'anticorps pour diagnostic d\'infection."},
    {code:"HERS",name:"*SEROLOGIE DE l’HERPES (1 et 2 )",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:400.00,description:"Test sérologique. Détection d\'anticorps pour diagnostic d\'infection."},
    {code:"HPS",name:"*SEROLOGIE DE L’HELICOBACTER PYLORI",sector:"Labo Spécialisé",delay:"A TELEPHONER",price:180.00,description:"Détection d\'Helicobacter pylori. Bactérie responsable d\'ulcères gastriques."},
    {code:"THYR",name:"*THYROGLOBULINE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:200.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"ASAT 0146",name:"TRANSAMINASE (ASAT/GOT)",sector:"LB",delay:"1 jour",price:100.00,description:"Enzyme hépatique et cardiaque (GOT/AST). Évalue les atteintes hépatiques et cardiaques."},
    {code:"TG 0134",name:"TRIGLYCERIDES",sector:"LB",delay:"1 jour",price:60.00,description:"Graisses circulantes. Évaluation du métabolisme lipidique et risque cardiovasculaire."},
    {code:"ALAT 0147",name:"TRANSAMINASE (ALAT/AST)",sector:"LB",delay:"1 jour",price:107.00,description:"Enzyme hépatique (GPT/ALT). Marqueur sensible de lésion des cellules du foie. Augmentée en hépatite."},
    {code:"TS 0237",name:"*TEMPS DE SAIGNEMENT (TS)",sector:"LH",delay:"1 jour",price:30.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"TCA 1 0239",name:"TEMPS DE CEPHALINE ACTIVEE (TCA)",sector:"LH",delay:"1 jour",price:40.00,description:"Temps de céphaline activée. Dépistage des troubles de la coagulation."},
    {code:"TP  1 0236",name:"TAUX DE PROTHROMBINE (TP)",sector:"LH",delay:"1 jour",price:40.00,description:"Taux de prothrombine. Évalue la coagulation. Surveillance des anticoagulants (AVK)."},
    {code:"PHADC HN",name:"*TEST DE SCREENING PNEUMA P",sector:"LIS",delay:"4 jours",price:500.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"PHADE HN",name:"*TEST DE SCREENING PNEUMA",sector:"LIS",delay:"4 jours",price:500.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"TROPO 0149",name:"*TROPONINE",sector:"LIC",delay:"1 jour",price:250.00,description:"Marqueur spécifique d\'infarctus du myocarde. Diagnostic urgent des syndromes coronariens."},
    {code:"TSH 0164",name:"TSH ULTRASENSIBLE",sector:"LIC",delay:"1 jour",price:200.00,description:"Hormone thyréostimulante. Test de référence pour dépistage des dysfonctions thyroïdiennes."},
    {code:"TSYNA XX75",name:"*TEST AU SYNACHTENE IMMEDIAT",sector:"LIC",delay:"2 jours",price:750.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"TRPHE             ( ",name:"*TROPHATOP(Enfant jusqu’a 15 ans)",sector:"LIS",delay:"4 jours",price:900.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"TRPHA( FX5,FX24,fx25",name:"*TROPHATOP(Adulte)",sector:"LIS",delay:"4 jours",price:900.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"TEST 0162",name:"TESTOSTERONE",sector:"LIC",delay:"1 jour",price:300.00,description:"Hormone masculine principale. Évalue la fonction testiculaire, fertilité et virilisation."},
    {code:"TGR 0194",name:"*TEST DE GROSSESSE URINAIRE",sector:"LIC",delay:"1 jour",price:80.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"TOXOG 0307",name:"TOXOPLASMOSE SERODIAGNOSTIC (IGG)",sector:"LIS",delay:"1 jour",price:100.00,description:"Sérologie toxoplasmose. Obligatoire pendant la grossesse. Risque fœtal si primo-infection."},
    {code:"TPHA 0286",name:"TPHA (QUANTITATIF)",sector:"LIS",delay:"1 jour",price:250.00,description:"Taux de prothrombine. Évalue la coagulation. Surveillance des anticoagulants (AVK)."},
    {code:"TOXOM 0308",name:"TOXOPLASMOSE SERODIAGNOSTIC (IGM)",sector:"LIS",delay:"1 jour",price:150.00,description:"Sérologie toxoplasmose. Obligatoire pendant la grossesse. Risque fœtal si primo-infection."},
    {code:"TRSF 0370",name:"*TRANSFERRINE",sector:"LP",delay:"1 jour",price:150.00,description:"Fer sérique. Diagnostic des anémies ferriprives et surcharge en fer."},
    {code:"TRES HN",name:"*TEST RESPIRATOIRE A L’UREE 13C",sector:"DTP",delay:"1 jour",price:600.00,description:"Déchet azoté reflétant la fonction rénale. Augmentée en cas d\'insuffisance rénale ou déshydratation."},
    {code:"U 0135",name:"UREE (SANG)",sector:"LB",delay:"1 jour",price:30.00,description:"Déchet azoté reflétant la fonction rénale. Augmentée en cas d\'insuffisance rénale ou déshydratation."},
    {code:"UU 0182",name:"UREE URINAIRE",sector:"LB",delay:"2 jours",price:30.00,description:"Déchet azoté reflétant la fonction rénale. Augmentée en cas d\'insuffisance rénale ou déshydratation."},
    {code:"VITB 0435",name:"*VITAMINE B12 (COBALAMINE)",sector:"LIC",delay:"3 jours",price:400.00,description:"Vitamine essentielle au système nerveux. Diagnostic des anémies et neuropathies."},
    {code:"VS 0223",name:"*V.S (VITESSE DE SEDIMENTATION)",sector:"LH",delay:"1 jour",price:30.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"VDRL 0284",name:"VDRL (QUANTITATIF)",sector:"LIS",delay:"1 jour",price:60.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"VRS",name:"VIROSES RESPIRATOIRES",sector:"DBS",delay:"5 jours",price:450.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"WR 1 0366",name:"*WAALER ROSE",sector:"LIS",delay:"1 jour",price:50.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CARNL",name:"CARNITINE LIBRE",sector:"LSM",delay:"15 jours",price:400.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"AAAM",name:"CHROMATOGRAPHIE DES ACIDES AMINES",sector:"LSM",delay:"15 jours",price:1600.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"ALAN",name:"ALANINE",sector:"LSM",delay:"15 jours",price:500.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"ARGI",name:"ARGININE",sector:"LSM",delay:"15 jours",price:500.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"ACAS",name:"ACIDE ASPARAGINIQUE",sector:"LSM",delay:"15 jours",price:500.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CITRU",name:"CITRULLINE",sector:"LSM",delay:"15 jours",price:500.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"ACGLU",name:"ACIDE GLUTAMIQUE",sector:"LSM",delay:"15 jours",price:500.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"GLYCI",name:"GLYCINE",sector:"LSM",delay:"15 jours",price:500.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"LEUCI",name:"LEUCINE",sector:"LSM",delay:"15 jours",price:500.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"METIO",name:"METHIONINE",sector:"LSM",delay:"15 jours",price:500.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"ORNI",name:"ORNITHINE",sector:"LSM",delay:"15 jours",price:500.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"PHENY",name:"PHENYLALANINE",sector:"LSM",delay:"15 jours",price:500.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"PROLI",name:"PROLINE",sector:"LSM",delay:"15 jours",price:500.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"TYROS",name:"TYROSINE",sector:"LSM",delay:"15 jours",price:500.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"VALIN",name:"VALINE",sector:"LSM",delay:"15 jours",price:500.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"TACRO",name:"TACROLIMUS",sector:"LSM",delay:"10 jours",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"EVERO",name:"EVEROLIMUS",sector:"LSM",delay:"10 jours",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"SIRO",name:"SIROLIMUS",sector:"LSM",delay:"10 jours",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CICL TX11",name:"CICLOSPORINE",sector:"LSM",delay:"10 jours",price:300.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"AOU",name:"ACIDE OROTIQUE URINAIRE",sector:"LSM",delay:"A TELEPHONER",price:1500.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"MPSU",name:"MUCOPOLYSACCHARIDES URINAIRE",sector:"LSM",delay:"A TELEPHONER",price:1800.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"ACYLC1",name:"DOSAGE DES ACYL CARNITINE",sector:"LSM",delay:"A TELEPHONER",price:400.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"CARNL",name:"CARNITINE LIBRE",sector:"LSM",delay:"A TELEPHONER",price:1200.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"AOU",name:"ACIDES ORGANIQUES",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:1800.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"HLAB",name:"HLAB27 ANTIGENE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:450.00,description:"Immunoglobulines E. Diagnostic des allergies et maladies parasitaires."},
    {code:"HLABG",name:"HLAB27 GENOTYPAGE",sector:"Labo. Spécialisé",delay:"A TELEPHONER",price:900.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."},
    {code:"BHELY BILAN D’HEMOLY",name:"LH/LP",sector:"7",delay:"390.00",price:30.00,description:"Dosage hormonal. Évalue le fonctionnement du système endocrinien et la fertilité."},
    {code:"BILPH3 BILAN DES ANT",name:"LIS/LH",sector:"4",delay:"1005.00",price:147.00,description:"Dosage hormonal. Évalue le fonctionnement du système endocrinien et la fertilité."},
    {code:"CATE CATECHOLAMINES ",name:"Labo. Spécialisé",sector:"A TELEPHONER",delay:"700.00",price:70.00,description:"Examen de laboratoire médical pour diagnostic et suivi thérapeutique."}
];

console.log(`✅ ${window.MEDICAL_DATABASE.length} analyses médicales chargées`);
console.log(`📋 ${Object.keys(window.SECTOR_NAMES).length} secteurs de laboratoire`);